### ISSUE TITLE
ios-objective-c-CocoaPods/Example/ Lỗi không nhận được callback

### ISSUE THREAD

**Issue by ldthai** [momo-wallet/mobile-sdk#11]
Sau khi thanh toán ứng dụng momo test không đóng và không trả kết quả về cho ứng dụng

**Comment by momodevelopment** [comment]
Bạn hãy mô tả rõ hơn về cách mà bạn cài đặt để tôi có thể kiểm tra ? 
Bạn đang cài đặt bằng iOS native ? hay React-native ?

và hãy đảm bảo rằng bạn đã thực hiện đầy đủ 3 bước cài đặt như Readme .
Step 1. Config file Plist
Step 2. Import SDK AppDelegate instance
Step 3. Update Layout Payment / Open MoMo app 
Tham khảo readme.
https://github.com/momo-wallet/mobile-sdk/blob/master/ios/README.md

**Comment by ldthai** [comment]
@momodevelopment  cám ơn bạn đã phản hồi!
Mình đã giải quyết được vấn đề!
