### ISSUE TITLE
ios/ios-swift-CocoaPods/Example/testapp001/ build bị lỗi

### ISSUE THREAD

**Issue by D271** [momo-wallet/mobile-sdk#12]
Build testapp001 bị báo lỗi như vầy:
:-1: Multiple commands produce '/Users/duyho/Library/Developer/Xcode/DerivedData/testapp001-caearthsttabstfdadolafanyksp/Build/Products/Debug-iphoneos/MomoiOSSwiftSdk/MomoiOSSwiftSdk.framework/Info.plist':
1) Target 'MomoiOSSwiftSdk' (project 'Pods') has copy command from '/Users/duyho/Desktop/mobile-sdk-master/ios/ios-swift-CocoaPods/Example/testapp001/Pods/MomoiOSSwiftSdk/MomoiOSvSwiftSdk/Info.plist' to '/Users/duyho/Library/Developer/Xcode/DerivedData/testapp001-caearthsttabstfdadolafanyksp/Build/Products/Debug-iphoneos/MomoiOSSwiftSdk/MomoiOSSwiftSdk.framework/Info.plist'
2) Target 'MomoiOSSwiftSdk' (project 'Pods') has process command with output '/Users/duyho/Library/Developer/Xcode/DerivedData/testapp001-caearthsttabstfdadolafanyksp/Build/Products/Debug-iphoneos/MomoiOSSwiftSdk/MomoiOSSwiftSdk.framework/Info.plist'

**Comment by momodevelopment** [comment]
Đây là lỗi phổ biến trên Xcode 10 , bạn có thể Tham khảo cásh xử lý tại 
https://stackoverflow.com/questions/50718018/xcode-10-error-multiple-commands-produce

File Info.plist cũng đã được remove ra khỏi framework để tránh lỗi Multiple commands, bạn hãy pod install và thử build lại.
