### ISSUE TITLE
Dữ liệu sai định dạng

### ISSUE THREAD

**Issue by doanphu** [momo-wallet/mobile-sdk#14]
api https://test-payment.momo.vn/pay/app
Content-Type:application/x-www-form-urlencoded
truyền params theo tài liệu https://developers.momo.vn/#/docs/app_in_app 
{
  "partnerCode": "MOMOIQA420180417",
  "customerNumber": "0966787273",
  "partnerRefId": "Merchant123556666",
  "appData": "v2/qml0PbOlrBYjFlZvXwRWjoMpmFmvqStTJt4DCXfE0cgMtyH5Akv+
FxL2Nu8lDmxt0P3Mu+YeCGB+UFfwXICo7D07jR6f2VhauglozphNgkK7724sO3qV
KC9ZI8KCdr0k4AHuuUNF4AT6Iy2rOmaCVF1WeyS/y/n2E4DArwaHG2J+8StiawfZP
iKoUGvywNHV",
 "hash":"A7WFmmnpn6TRX42Akh/iC5DdU5hhBT9LR5QSG6rJAl70hfEkkGUx2pTCai8s
+M9KMVUcJ7m52iv74yhmeEjjN10TtEJoqITBIYBG2bqcTprhDijyhV4ePU7ytDNuLxzzIv
GfTYyvbsEJ2jZTSf556yod12vhYqOJSFL/U2hVuxjUahf5Rnu5R/OLalg8QmlU6nQooEuN
dzEXPMd6j9EaxOCiB2oM5/9QiTN0tCNSTIVvPtnlHu5mIbBHChcwfToIL4IAiD1nbrlDuB
X//CZcrZj6hFqjvU31yb/DuG02c3aqWxbZKZ8csOwF9bL30m/yGr/0BQUWgunpDPrmCosf9A==",
  "description": "Thanh toan cho don hang Merchant123556666 qua MoMo",
  "version": 2,
  "payType": 3
}
nhưng nhận về {
    "status": 2400,
    "message": "Dữ liệu sai định dạng."
}

**Comment by momodevelopment** [comment]
Chào @doanphu ,
Theo tài liệu, sample mẫu chỉ mang tính Tham khảo và Không dùng được để thanh toán. 
Hãy đảm bảo rằng bạn thực hiện đúng nghiệp vụ luồng thanh Toán App-In-App.
Theo sơ đồ xử lý, Bộ dữ liệu gửi đi thanh toán ở Server (bước 4) phải được lấy từ Client tuân thủ  Theo Bước (1) -> (2) -> (3).

**Comment by doanphu** [comment]
hi Quang Lukas, mình thực hiện đúng theo quy trình từ bước 1 -> 2 -> 3, vấn đề ở đây là những parameter mình truyền vào để thực hiện request lên momo thì momo trả về sai định dạng (giống như parameter truyền vào sai key...) nên mình muốn biết chính xác parameter mình cần truyền là những trường nào 
Thank vì đã phản hồi

**Comment by momodevelopment** [comment]
Bạn có thể Tham khảo thêm cách giải quyết vấn đề tại 
https://github.com/momo-wallet/mobile-sdk/issues/15
