### ISSUE TITLE
Could not find com.github.momo-walet:mobile-sdk:1.0.2

### ISSUE THREAD

**Issue by kuztta** [momo-wallet/mobile-sdk#2]
I encountered an error when integrating momo sdk in to my app
![picturemessage_rs1tpw0l szg](https://user-images.githubusercontent.com/21176745/51018359-e2c92480-15a9-11e9-99c3-085abe5b9163.png)
Thanks!

**Comment by LanhLuu** [comment]
Try to add jitpack into repositories 
maven {
            url "https://jitpack.io"
        }

Example build.gradle:
`buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url "https://jitpack.io"
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
`
