### ISSUE TITLE
Website based solution

### ISSUE THREAD

**Issue by alexsonphoenix** [momo-wallet/mobile-sdk#31]
Hi, I'm configuring MOMO payment to a website, have you implemented MOMO as payment method on an e-commerce website, please let me know. I'm having difficulties going around this

**Comment by hainguyenp207** [comment]
Hi @alexsonphoenix, We have already provided payment methods on online platforms such as e-commerce, booking-online, etc..
You can refer in this link https://developers.momo.vn/#/docs/aio/
Let us know if you have any questions.
