### ISSUE TITLE
[React Native - iOS] Momo Response Issue

### ISSUE THREAD

**Issue by ncdai3651408** [momo-wallet/mobile-sdk#5]
Hi MoMo Team!

I am having problems with React Native MoMo SDK on iOS.

How to determine if the **user does not open the MoMo App** or the **user does not download the App** or the **user exits the app** on the phone _(does not receive a token)_.

Currently I can only handle when I receive a token.
`EventEmitter.addListener('RCTMoMoNoficationCenterRequestTokenReceived', this.handleMomoResponse)`

I want to receive one event like : **RCTMoMoNoficationCenterRequestTokenFailed**

 Please help me solve this problem.

Thank you so much!

**Comment by momodevelopment** [comment]
@ncdai3651408 
We have updated new event name **RCTMoMoNoficationCenterRequestTokenState** to cover issues as status 
status  = 0 **Parameters valid. Ready to open MoMo app** 
status = 1 **canOpenURL failed for URL MoMo app** 
status = 2 **Parameters invalid** 

usage react-native-momosdk@1.2.6 
EventEmitter.addListener('RCTMoMoNoficationCenterRequestTokenState',(response) => {
     //UX definition
})

Hope this change will help you!

**Comment by LanhLuu** [comment]
useful!

**Comment by momodevelopment** [comment]
@ncdai3651408
We have updated new event name RCTMoMoNoficationCenterRequestTokenState to cover issues as status
status = 0 **Parameters valid. Ready to open MoMo app**
status = 1 **canOpenURL failed for URL MoMo app**, _user does not download the App_ or _LSApplicationQueriesSchemes config not finished_
status = 2 **Parameters invalid**

usage react-native-momosdk@1.2.6
```
EventEmitter.addListener('RCTMoMoNoficationCenterRequestTokenState',(response) => {
     //UX definition
})
```

Hope this change will help you!

**Comment by momodevelopment** [comment]
@ncdai3651408
We have updated new event name RCTMoMoNoficationCenterRequestTokenState to cover issues as status
status = 0 **Parameters valid. Ready to open MoMo app** - _user exits the app_
status = 1 **canOpenURL failed for URL MoMo app**, _user does not download the App_ or _LSApplicationQueriesSchemes config not finished_
status = 2 **Parameters invalid**

usage react-native-momosdk@1.2.6
```
EventEmitter.addListener('RCTMoMoNoficationCenterRequestTokenState',(response) => {
     //UX definition
})
```

Hope this change will help you!

**Comment by momodevelopment** [comment]
@ncdai3651408
We have updated the event name **RCTMoMoNoficationCenterRequestTokenState** to cover issues  
status = 0 **Parameters valid. Ready to open MoMo app** - _user exits the app_
status = 1 **canOpenURL failed for URL MoMo app**, _user does not download the App_ or _LSApplicationQueriesSchemes config not finished_
status = 2 **Parameters invalid**

npm install the latest version 
usage react-native-momosdk@1.2.5
```
EventEmitter.addListener('RCTMoMoNoficationCenterRequestTokenState',(response) => {
     //UX definition
})
```

Hope this change will help you!
