### ISSUE TITLE
Điều hướng đến CHPlay dù app đã được tải về máy khi yêu cầu thực thi mở app MoMo - Android Java

### ISSUE THREAD

**Issue by iammin99** [momo-wallet/mobile-sdk#51]
Xin chào, em setup chính xác như docs nhưng khi thực thi action mở app MoMo thì cứ điều hướng tới CHPlay thay vì MoMo App dù app đã được tải về thiết bị.
Mong nhận được hướng giải quyết sớm từ nhà phát triển. Cảm ơn nhiều ạ.
MoMo SDK version: 1.0.6
Android SDK version: 30

**Comment by vanhungpc** [comment]
> Xin chào, em setup chính xác như docs nhưng khi thực thi action mở app MoMo thì cứ điều hướng tới CHPlay thay vì MoMo App dù app đã được tải về thiết bị.
> Mong nhận được hướng giải quyết sớm từ nhà phát triển. Cảm ơn nhiều ạ.
> MoMo SDK version: 1.0.6
> Android SDK version: 30

bạn @iammin99 có đang dùng app momo test được tải từ link này không
https://developers.momo.vn/#/docs/testing_information
Bản app momo test mới nhất là phiên bản 30151
Hiện tại do bên mình đã đổi lại applicationId cho toàn bộ app test mới.

**Comment by iammin99** [comment]
> bạn @iammin99 có đang dùng app momo test được tải từ link này không
> https://developers.momo.vn/#/docs/testing_information
> Bản app momo test mới nhất là phiên bản 30151
> Hiện tại do bên mình đã đổi lại applicationId cho toàn bộ app test mới.

À dạ em đã hiểu và làm được rồi ạ. Cảm ơn anh nhiều.
