### ISSUE TITLE
About neact native event listen on multi app have using momo

### ISSUE THREAD

**Issue by WMaximusW** [momo-wallet/mobile-sdk#6]
Hi Momo team,
My problem is that i have two app that using momo (app A using react-native, app B using swift), i'm using same account business momo for both app, but when i open app A to working with momo, momo always call back to app B. I think my problem relate to eventlistener. Did i do something wrong? Please help! tks

**Comment by momodevelopment** [comment]
Momo app callback to partner app through 'appScheme' parameter (iOS only). 
if you have one more app, you need to change 'appScheme' value.

**Comment by WMaximusW** [comment]
> Momo app callback to partner app through 'appScheme' parameter (iOS only).
> if you have one more app, you need to change 'appScheme' value.

I create other account and paste new partnerSchemeId but still not working like you said.

**Comment by WMaximusW** [comment]
> Momo app callback to partner app through 'appScheme' parameter (iOS only).
> if you have one more app, you need to change 'appScheme' value.
Thank you! It works
