### ISSUE TITLE
[React Native Android] Lỗi khi sử dụng RNMomosdkPackage cùng với FBSDKPackage

### ISSUE THREAD

**Issue by ncdai3651408** [momo-wallet/mobile-sdk#7]
Hi MoMo Dev Team!

### Vấn đề
Hiện tại mình đang gặp vấn đề khi sử dụng **RNMomosdkPackage** cùng với **FBSDKPackage**.
Khi mình login bằng Facebook => App sẽ mở browser lên để xác nhận => Khi xác nhận thành công thì App bị crash.

### Tìm hiểu
Sau gần nửa ngày mình tìm hiểu lỗi Crash App _(kiểm tra lại các version, check lại code các version app trước của mình => Login with FB vẫn okay)_. Điểm khác biệt duy nhất ở App version hiện tại với các version trước là mình có cài thêm **RNMomosdkPackage**

- Mình đã thử tắt **RNMomosdkPackage** tạm thời => Thì mình Login with FB bình thường ([Demo](https://www.dropbox.com/s/8xaolxrj3cf1o5l/Use%20only%20FB%20SDK.mov?dl=0))

- Nhưng khi bật lại **RNMomosdkPackage** => App bị crash khi mình đã xác nhận fb thành công ([Demo](https://www.dropbox.com/s/j1xz5e8fb0arc5i/Use%20MOMO%20SDK%20and%20FB%20SDK.mov?dl=0))

Vậy lỗi Crash App là do đã sử dụng **RNMomosdkPackage** và **FBSDKPackage**

Mình vẫn chưa hiểu nguyên nhân vì sau có sự xung đột như vậy giữa 2 packages.

Mong Team Dev MoMo kiểm tra lại giúp mình **RNMomosdkPackage** nhé.

_Mình cung cấp thêm 1 số thông tin :_

**Packages Version**

- react-native : 0.57.8

- react-native-fbsdk : ^0.8.0

- react-native-momosdk : 1.2.5

- buildToolsVersion : 27.0.3

- minSdkVersion : 21

- compileSdkVersion : 27

- targetSdkVersion : 26

- supportLibVersion : "27.1.1"

**MainApplication.java => getPackages()**

![image](https://user-images.githubusercontent.com/10192821/58888569-cde45d80-8711-11e9-8b71-01e08378251f.png)

**Dependencies**

![image](https://user-images.githubusercontent.com/10192821/58888712-07b56400-8712-11e9-929a-bc2ad2e59550.png)

Thank you!

**Comment by mrtaiw** [comment]
bạn fork về mở react-native-momosdk/android/src/main/java/com/reactlibrary/RNMomosdkModule.java thêm condition request_code vào là được
![image](https://user-images.githubusercontent.com/4935988/58938595-62e16800-879f-11e9-9b52-5364e2e51f88.png)

**Comment by ncdai3651408** [comment]
@momodevelopment Bạn support giúp mình trường hợp này nha!

**Comment by momodevelopment** [comment]
Hi @ncdai3651408 
Dev team đã chỉnh sửa lỗi này trên version 1.2.7
`$ npm install react-native-momosdk`
Thanks so much!

**Comment by ncdai3651408** [comment]
Hi @momodevelopment 
Cảm ơn Team Dev rất nhiều :D Lần sau hy vọng Team Reply các issue trên GitHub nhanh hơn xíu nha <3

**Comment by momodevelopment** [comment]
Thanks so much!
