### ISSUE TITLE
[React Native - Andoird] Task :react-native-momosdk:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by nivianh** [momo-wallet/mobile-sdk#8]
Hi Dev Team,

When I run terminal: 
$ cd android
$ ./gradlew assembleRelease

I get this error
**> Task :react-native-momosdk:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.**

Info:
buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.0"

package.json:
"react-native": "0.59.9",
"react-native-momosdk": "^1.2.7"

Thank's

**Comment by nivianh** [comment]
@momodevelopment Can you help me?

**Comment by momodevelopment** [comment]
I did a quick test by building the apk. It's work normal, not happen like yours.
I think it's not an error from momo-sdk. double check it.

**See the sample code
https://github.com/momodevelopment/momosdk-react-native/

**Comment by nivianh** [comment]
Hi,

In your sample code
```
buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```
My build.gradle file
```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```
package.json file

`"react-native-momosdk": "^1.2.7"`

and I get a warning

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools

Thank's

**Comment by nivianh** [comment]
I still get the same error, can help me?

**Comment by LanhLuu** [comment]
See my video @nivianh 
https://youtu.be/-757xOUz_cw

Hope this sample help you! :)

**Comment by nivianh** [comment]
Hi @LanhLuu 
You can check on my demo repository

[](https://github.com/nivianh/MomoRN)
and attached image
https://drive.google.com/file/d/1leALvLM5K2RpQJW03QrLlgHjn5GD-eWv/view

**Comment by nivianh** [comment]
Hi @momodevelopment 
You can reopen this issue?

Thank's

**Comment by momodevelopment** [comment]
I have updated the targetSdkVersion to 28.0.3
get the latest version react-native-momosdk and npm install @nivianh 
Thanks!

**Comment by nivianh** [comment]
Thank you very much!
